### ISSUE TITLE
Documentation missing for TelnetStreamReader and TelnetStreamWriter

### ISSUE THREAD

**Issue by flip111** [jquast/telnetlib3#28]
At the bottom of [this page](https://telnetlib3.readthedocs.io/en/latest/api/client.html) there is:

```
Return (reader, writer):
    The reader is a TelnetStreamReader instance, the writer is a TelnetStreamWriterinstance.
```

Both `TelnetStreamReader` and `TelnetStreamWriter` are not clickable. When i [search](https://telnetlib3.readthedocs.io/en/latest/search.html?q=TelnetStreamReader&check_keywords=yes&area=default#) for `TelnetStreamReader` i get `client`, `stream_reader` and `server`. The `stream_reader` page has class `TelnetReader` and the other two pages also don't contain the class definition of `TelnetStreamReader`

**Comment by jquast** [comment]
fixed.
