### ISSUE TITLE
Tests are not Python 3.7 compatible

### ISSUE THREAD

**Issue by jayvdb** [jquast/telnetlib3#38]
```
[   49s] /usr/lib/python3.7/site-packages/_pytest/python.py:507: in _importtestmodule
[   49s]     mod = self.fspath.pyimport(ensuresyspath=importmode)
[   49s] /usr/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
[   49s]     __import__(modname)
[   49s] E     File "/home/abuild/rpmbuild/BUILD/telnetlib3-1.0.2/archived_tests/test_bsdtelnet.py", line 49
[   49s] E       yield from child.expect("telnet> ", async=True)
[   49s] E                                               ^
[   49s] E   SyntaxError: invalid syntax
```

These cause `pytest` without arguments to fail, as it tries to find tests.

One solution for that is to include pytest configuration in `setup.cfg` which tests pytest where to look for the tests, i.e. not `archived_tests`

**Comment by jquast** [comment]
yes, i understand why,  I'll do my best to help sometime, no promises, very busy lately

I try to maintain the pexpect library, too, where this keyword used to exist, this was an older version of that library early around python 3.3 before `async` keyword happened, this can be easily updated or deleted, I'm not sure we should depend upon external bsd telnet, anyway, these tests were for my own enjoyment.

**Comment by jquast** [comment]
I've deleted those tests.
