### ISSUE TITLE
TelnetReader returns incorrect class string, instead of bytes

### ISSUE THREAD

**Issue by dmfigol** [jquast/telnetlib3#47]
Hi,
I've noticed that the `TelnetReader` is inheriting from `asyncio.StreamReader`, however its `read` method returns `str`, instead of `bytes` like its parent.
https://github.com/jquast/telnetlib3/blob/master/telnetlib3/stream_reader.py#L147
https://github.com/python/typeshed/blob/5d553c9584eb86793cfa61019ddee5c7b62bc286/stdlib/3/asyncio/streams.pyi#L101
This causes issues when we try to type check the code, but also adds confusion, since classes which implement `asyncio.StreamReader` interface now follow different rules.

**Comment by jquast** [comment]
Yes, we should not derive from stream reader. Sorry that happened back when asyncio was called “tulip” and wasn’t very very clear how the interfaces would work :)

This library handles renegotiation of encoding, or bytes-only interface (for file transfers, for example), and we shouldn’t pretend to be anything like the StreamReader/writer, thank you for your bug report

**Comment by jquast** [comment]
I fixed Writer in cecceb8afa0d53968e1cf52522dd93bd4f4e462c hope to fix Reader soon

**Comment by jquast** [comment]
Reader is also fixed, in d5cf4367cf6791223342e32b0a1285b1e63ee4f0

**Comment by jquast** [comment]
Closed by release of 2.0.1 https://telnetlib3.readthedocs.io/en/master/history.html#history
