### ISSUE TITLE
Tab,Backspace,Arrow not working

### ISSUE THREAD

**Issue by arunstar** [jquast/telnetlib3#49]
I am running telnet server using telnetlib3 and trying to connect it from another server, when i press tab/backspace , it doesn't do anything. I have used the same code as the war game.

Do I have add some functions to handle the key press like tab/delete?

**Comment by jquast** [comment]
Yes, these are special application keys, the war game only demos a single y/n prompt, to simplify the reality of “decoding multibyte application key sequences” :)

I maintain another library, blessed, that does just that, it becomes difficult for different terminal types and so on, this telnetlib3 doesn’t help there, maybe I should plug these two into each other sometime.

But there is a built-in shell that handles some of them (backspace, tab), not arrows though, if you run telnetlib3-server without any arguments that prompt is used, and you can also import and use it https://github.com/jquast/telnetlib3/blob/master/telnetlib3/server_shell.py#L64

I’d love to see someone plug in something like bpython, best wishes!

**Comment by jquast** [comment]
By the way, if you install the library, try ``telnetlib3-server`` from command line, this has backspace and tab working if i recall
