### ISSUE TITLE
Timeout crashes the telnetlib server

### ISSUE THREAD

**Issue by zofy** [jquast/telnetlib3#51]
Hello,
I've encountered a server crash after the timeout occurred. I think the issue was introduced after he circular reference was broken: https://github.com/jquast/telnetlib3/pull/44/commits/782c67788cc009bd602e0b7f37490153e12dbbce

Let's start a simple telnetlib sever with timeout set to 5 seconds.
````
import asyncio, telnetlib3

@asyncio.coroutine
def shell(reader, writer):
    writer.write('\r\nWould you like to play a game? ')
    inp = yield from reader.read(1)
    if inp:
        writer.echo(inp)
        writer.write('\r\nThey say the only way to win '
                     'is to not play at all.\r\n')
        yield from writer.drain()
    writer.close()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    coro = telnetlib3.create_server(port=8023, shell=shell, timeout=5)
    server = loop.run_until_complete(coro)
    loop.run_until_complete(server.wait_closed())

````
After the server is started and client makes a connection (`telnet localhost 8023`). After 5 seconds, the server crashes with:
```
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<shell() done, defined at ex.py:3> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  ...
 <home>/.local/lib/python3.8/site-packages/telnetlib3/stream_reader.py", line 125, in decode
    encoding = self.fn_encoding(incoming=True)
TypeError: 'NoneType' object is not callable
```
Could you verify that this is a bug?
IMHO the TelnetReaderUnicode.read() should be able to take the timeout into account. What do you think?

**Comment by jquast** [comment]
I made 2 additional fixes and merged to master,
- check fn_encoding is callable in ``__repr__``
- check for EOF in decode, necessary when read_exactly(1) gets EOF instead

i'll release to pypi in 8 or more hours

**Comment by jquast** [comment]
this fix is going to pypi shortly as 1.0.4

**Comment by jquast** [comment]
https://pypi.org/project/telnetlib3/1.0.4/

**Comment by zofy** [comment]
Thank you, great job!
