### ISSUE TITLE
How to close connection properly?

### ISSUE THREAD

**Issue by zljubisic** [jquast/telnetlib3#55]
If I get client_reader/writer with:

`client_reader, client_writer = telnetlib3.open_connection(host=self._host, port=self._port)`

How to close the connection properly?
I expected this to work:

```
client_writer.close()
client_writer.wait_closed()
```

The first command passes with no exceptions, but on the second one I get:
```
...
/opt/python/miniconda3/envs/jlab/lib/python3.8/asyncio/streams.py in wait_closed(self)
    358     async def wait_closed(self):
--> 359         await self._protocol._get_close_waiter(self)
    360 

AttributeError: 'NoneType' object has no attribute '_get_close_waiter'
```

What is the proper way of closing the connection?
Is client_writer.close() enough?

Or maybe I should:

client_writer.write('exit" + '\r\n')
await asyncio.wait_for(client_writer.drain(), timeout=timeout_secs)

Regards

**Comment by jquast** [comment]
sorry, I haven't worked on this project in a while I'm trying to return to it, this looks related to recent bugs/changes, I wonder if this still happens from master branch? anyway, the way you are trying to close looks correct, we should make the code work this way.

**Comment by zljubisic** [comment]
Hi @jquast 
Is client_writer.close() enough or I should:
client_writer.write('exit" + '\r\n')
await asyncio.wait_for(client_writer.drain(), timeout=timeout_secs)

Which one is more reliable?

**Comment by jquast** [comment]
rain only matters if you care to know that all output is written to the other side before closing. For example a system that says "goodbye", you want to ensure all of the letters of "goodbye" are written before socket is closed.
